api:
  jph:
    domain: "jsonplaceholder.typicode.com"
    endpoints:
      user: "/users"
      post: "/posts"

database: 
  postgres: "db_forum"

spring:
  datasource:
    driverClassName: "org.hibernate.dialect.PostgreSQLDialect"
    url: "jdbc:postgresql://localhost:5432/${database.postgres}"
    username: "localhost"
    password: "AndyAE_2209"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update
  # Hibernate ddl auto (create, create-drop, validate, update)